before_all do
  skip_docs
end

lane :release_mobile do
  gradle(task: 'mobile:app:bundleRelease')
  upload_to_play_store(
    skip_upload_apk: true,
    aab: 'mobile/app/build/outputs/bundle/release/app-release.aab',
  )
end

lane :release_wear do
  gradle(task: 'wear:app:bundleRelease')
  upload_to_play_store(
    track: 'wear:production',
    skip_upload_apk: true,
    aab: 'wear/app/build/outputs/bundle/release/app-release.aab',
  )
end
